//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/ActionMap/GameInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/ActionMap/GameInputActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @GameInputActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @GameInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""GameInputActions"",
    ""maps"": [
        {
            ""name"": ""FirstPlayer"",
            ""id"": ""585dc676-e043-476d-9996-c0321c260957"",
            ""actions"": [
                {
                    ""name"": ""fpMove"",
                    ""type"": ""Value"",
                    ""id"": ""60aec252-9a1c-46cd-aace-5ac4b4ea0a4d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""fpTakeUp"",
                    ""type"": ""Button"",
                    ""id"": ""ba178d44-af6c-4b8f-acc5-9fb363dba003"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""fpLeftOut"",
                    ""type"": ""Button"",
                    ""id"": ""e1b192b9-4c5c-4fb6-81c6-4f695912ba08"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""5cb35604-a3ae-486b-b899-9d2a8b644b55"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fpMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8e2543bd-a952-4624-b6a3-738e2e011fa7"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/stick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fpMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5b54f5bf-8fbf-4ff3-9b73-54b364b018c8"",
                    ""path"": ""<Joystick>/stick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fpMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5cbca437-ef65-41f0-bde5-4b839e9bd6b7"",
                    ""path"": ""<Joystick>/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fpMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ab867bb2-f9a8-4665-a025-89d3f5029f99"",
                    ""path"": ""<Joystick>/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fpMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""2d7ca732-9ecc-4f43-90cf-c0f62a276061"",
                    ""path"": ""<Joystick>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fpTakeUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c248a034-df9b-49e0-951f-9599da1c5236"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fpLeftOut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""SecondPlayer"",
            ""id"": ""94aaf19a-109f-4261-91fb-322efd0be1a8"",
            ""actions"": [
                {
                    ""name"": ""spMove"",
                    ""type"": ""Value"",
                    ""id"": ""7d095b41-4ef6-4f2f-beea-44f2901bc9ba"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""spTakeUp"",
                    ""type"": ""Button"",
                    ""id"": ""014e18d0-0e96-44cd-931d-3c02e3bae4f1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""spLeftOut"",
                    ""type"": ""Button"",
                    ""id"": ""f9c88799-9042-464d-8b11-53b7310a4c2f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""8da2d0b4-fb75-4fca-b13d-cab251b325b8"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""spMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""3a015067-31bc-4950-87b3-1c10300c5033"",
                    ""path"": ""<Joystick>/stick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""spMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b4466488-5f65-42d8-89e0-c1a4df0bca40"",
                    ""path"": ""<Joystick>/stick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""spMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""35d0cf76-aadb-4080-abbf-3843815ded1c"",
                    ""path"": ""<Joystick>/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""spMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f41d6eb4-7c2e-427a-90a4-1d80833715ed"",
                    ""path"": ""<Joystick>/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""spMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""414ee379-1d2f-49cb-bb1e-3823b6cc134a"",
                    ""path"": ""<Joystick>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""spTakeUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2df23a0-0de6-4041-a44f-377c3a4f546b"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""spLeftOut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ThirdPlayer"",
            ""id"": ""730c2c1a-f1e0-48e4-bb29-be7a1ff49d81"",
            ""actions"": [
                {
                    ""name"": ""tpMove"",
                    ""type"": ""Value"",
                    ""id"": ""123712ad-7719-4850-9aac-dd6907173ba9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""tpTakeUp"",
                    ""type"": ""Button"",
                    ""id"": ""79b0074e-cbb3-413a-b4af-40c000b4a02c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""tpLeftOut"",
                    ""type"": ""Button"",
                    ""id"": ""8d03c845-f0ac-4128-a5c8-ceed2e15ce16"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""2e3f2fa8-0a96-4f13-8776-1f6846f8ad03"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""tpMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""631b7a01-9da7-4c22-8aa4-521bf400d260"",
                    ""path"": ""<Joystick>/stick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""tpMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""61a6a626-aa34-4b9d-b57e-84074ceceff1"",
                    ""path"": ""<Joystick>/stick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""tpMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d7f49b5c-5cc5-43d1-8191-0e0a483d237f"",
                    ""path"": ""<Joystick>/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""tpMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e1f1c959-645a-4219-aa61-b76ab4fa150d"",
                    ""path"": ""<Joystick>/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""tpMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""60f1796b-0040-4195-94cc-3d4d6922c3db"",
                    ""path"": ""<Joystick>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""tpTakeUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6974960a-75b5-4913-be02-0109db3a66b5"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""tpLeftOut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""FourPlayer"",
            ""id"": ""67e526b7-c370-4915-8f61-2606d8ce2783"",
            ""actions"": [
                {
                    ""name"": ""fopMove"",
                    ""type"": ""Value"",
                    ""id"": ""c179cd0f-458d-4274-9e42-2ee1e803d3e6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""fopTakeUp"",
                    ""type"": ""Button"",
                    ""id"": ""13a248d2-191f-44ec-ba08-a6b41c5097c6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""fopLeftOut"",
                    ""type"": ""Button"",
                    ""id"": ""a7bf4d5b-e61a-4263-a1b2-512cae92ac99"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""067e1c39-17a2-4151-b8ca-a9670fc3d43d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fopMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""654a7ede-5ce3-4099-a2d2-22aa297986f3"",
                    ""path"": ""<Joystick>/stick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fopMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4b80da72-3e6d-4689-b0d1-d9a331aeb273"",
                    ""path"": ""<Joystick>/stick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fopMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""78e71419-f457-4afa-8c23-04ef88a85cc0"",
                    ""path"": ""<Joystick>/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fopMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9f6a8591-aeb1-4553-99b8-4b95a3f92517"",
                    ""path"": ""<Joystick>/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fopMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c3eb18e3-1823-431d-848c-f3a49f541739"",
                    ""path"": ""<Joystick>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fopTakeUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6013abc8-db59-4746-b60d-107a211dcb65"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fopLeftOut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""36867b5e-40a2-4f97-b096-04ec859b5eec"",
            ""actions"": [
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""d192fb28-fcc8-4b20-83a9-53637cb17cd8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Resume"",
                    ""type"": ""Button"",
                    ""id"": ""1192e77d-0702-4361-bdca-b690d3bd83e1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3bff8e92-63e9-4d23-a542-e2c2b9484b28"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a513c69-e06f-432b-8b10-52930433726f"",
                    ""path"": ""<HID::DragonRise Inc.   Generic   USB  Joystick  >/button10"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Resume"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // FirstPlayer
        m_FirstPlayer = asset.FindActionMap("FirstPlayer", throwIfNotFound: true);
        m_FirstPlayer_fpMove = m_FirstPlayer.FindAction("fpMove", throwIfNotFound: true);
        m_FirstPlayer_fpTakeUp = m_FirstPlayer.FindAction("fpTakeUp", throwIfNotFound: true);
        m_FirstPlayer_fpLeftOut = m_FirstPlayer.FindAction("fpLeftOut", throwIfNotFound: true);
        // SecondPlayer
        m_SecondPlayer = asset.FindActionMap("SecondPlayer", throwIfNotFound: true);
        m_SecondPlayer_spMove = m_SecondPlayer.FindAction("spMove", throwIfNotFound: true);
        m_SecondPlayer_spTakeUp = m_SecondPlayer.FindAction("spTakeUp", throwIfNotFound: true);
        m_SecondPlayer_spLeftOut = m_SecondPlayer.FindAction("spLeftOut", throwIfNotFound: true);
        // ThirdPlayer
        m_ThirdPlayer = asset.FindActionMap("ThirdPlayer", throwIfNotFound: true);
        m_ThirdPlayer_tpMove = m_ThirdPlayer.FindAction("tpMove", throwIfNotFound: true);
        m_ThirdPlayer_tpTakeUp = m_ThirdPlayer.FindAction("tpTakeUp", throwIfNotFound: true);
        m_ThirdPlayer_tpLeftOut = m_ThirdPlayer.FindAction("tpLeftOut", throwIfNotFound: true);
        // FourPlayer
        m_FourPlayer = asset.FindActionMap("FourPlayer", throwIfNotFound: true);
        m_FourPlayer_fopMove = m_FourPlayer.FindAction("fopMove", throwIfNotFound: true);
        m_FourPlayer_fopTakeUp = m_FourPlayer.FindAction("fopTakeUp", throwIfNotFound: true);
        m_FourPlayer_fopLeftOut = m_FourPlayer.FindAction("fopLeftOut", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Pause = m_UI.FindAction("Pause", throwIfNotFound: true);
        m_UI_Resume = m_UI.FindAction("Resume", throwIfNotFound: true);
    }

    ~@GameInputActions()
    {
        UnityEngine.Debug.Assert(!m_FirstPlayer.enabled, "This will cause a leak and performance issues, GameInputActions.FirstPlayer.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_SecondPlayer.enabled, "This will cause a leak and performance issues, GameInputActions.SecondPlayer.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_ThirdPlayer.enabled, "This will cause a leak and performance issues, GameInputActions.ThirdPlayer.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_FourPlayer.enabled, "This will cause a leak and performance issues, GameInputActions.FourPlayer.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_UI.enabled, "This will cause a leak and performance issues, GameInputActions.UI.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // FirstPlayer
    private readonly InputActionMap m_FirstPlayer;
    private List<IFirstPlayerActions> m_FirstPlayerActionsCallbackInterfaces = new List<IFirstPlayerActions>();
    private readonly InputAction m_FirstPlayer_fpMove;
    private readonly InputAction m_FirstPlayer_fpTakeUp;
    private readonly InputAction m_FirstPlayer_fpLeftOut;
    /// <summary>
    /// Provides access to input actions defined in input action map "FirstPlayer".
    /// </summary>
    public struct FirstPlayerActions
    {
        private @GameInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public FirstPlayerActions(@GameInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "FirstPlayer/fpMove".
        /// </summary>
        public InputAction @fpMove => m_Wrapper.m_FirstPlayer_fpMove;
        /// <summary>
        /// Provides access to the underlying input action "FirstPlayer/fpTakeUp".
        /// </summary>
        public InputAction @fpTakeUp => m_Wrapper.m_FirstPlayer_fpTakeUp;
        /// <summary>
        /// Provides access to the underlying input action "FirstPlayer/fpLeftOut".
        /// </summary>
        public InputAction @fpLeftOut => m_Wrapper.m_FirstPlayer_fpLeftOut;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_FirstPlayer; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="FirstPlayerActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(FirstPlayerActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="FirstPlayerActions" />
        public void AddCallbacks(IFirstPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_FirstPlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FirstPlayerActionsCallbackInterfaces.Add(instance);
            @fpMove.started += instance.OnFpMove;
            @fpMove.performed += instance.OnFpMove;
            @fpMove.canceled += instance.OnFpMove;
            @fpTakeUp.started += instance.OnFpTakeUp;
            @fpTakeUp.performed += instance.OnFpTakeUp;
            @fpTakeUp.canceled += instance.OnFpTakeUp;
            @fpLeftOut.started += instance.OnFpLeftOut;
            @fpLeftOut.performed += instance.OnFpLeftOut;
            @fpLeftOut.canceled += instance.OnFpLeftOut;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="FirstPlayerActions" />
        private void UnregisterCallbacks(IFirstPlayerActions instance)
        {
            @fpMove.started -= instance.OnFpMove;
            @fpMove.performed -= instance.OnFpMove;
            @fpMove.canceled -= instance.OnFpMove;
            @fpTakeUp.started -= instance.OnFpTakeUp;
            @fpTakeUp.performed -= instance.OnFpTakeUp;
            @fpTakeUp.canceled -= instance.OnFpTakeUp;
            @fpLeftOut.started -= instance.OnFpLeftOut;
            @fpLeftOut.performed -= instance.OnFpLeftOut;
            @fpLeftOut.canceled -= instance.OnFpLeftOut;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="FirstPlayerActions.UnregisterCallbacks(IFirstPlayerActions)" />.
        /// </summary>
        /// <seealso cref="FirstPlayerActions.UnregisterCallbacks(IFirstPlayerActions)" />
        public void RemoveCallbacks(IFirstPlayerActions instance)
        {
            if (m_Wrapper.m_FirstPlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="FirstPlayerActions.AddCallbacks(IFirstPlayerActions)" />
        /// <seealso cref="FirstPlayerActions.RemoveCallbacks(IFirstPlayerActions)" />
        /// <seealso cref="FirstPlayerActions.UnregisterCallbacks(IFirstPlayerActions)" />
        public void SetCallbacks(IFirstPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_FirstPlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FirstPlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="FirstPlayerActions" /> instance referencing this action map.
    /// </summary>
    public FirstPlayerActions @FirstPlayer => new FirstPlayerActions(this);

    // SecondPlayer
    private readonly InputActionMap m_SecondPlayer;
    private List<ISecondPlayerActions> m_SecondPlayerActionsCallbackInterfaces = new List<ISecondPlayerActions>();
    private readonly InputAction m_SecondPlayer_spMove;
    private readonly InputAction m_SecondPlayer_spTakeUp;
    private readonly InputAction m_SecondPlayer_spLeftOut;
    /// <summary>
    /// Provides access to input actions defined in input action map "SecondPlayer".
    /// </summary>
    public struct SecondPlayerActions
    {
        private @GameInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public SecondPlayerActions(@GameInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "SecondPlayer/spMove".
        /// </summary>
        public InputAction @spMove => m_Wrapper.m_SecondPlayer_spMove;
        /// <summary>
        /// Provides access to the underlying input action "SecondPlayer/spTakeUp".
        /// </summary>
        public InputAction @spTakeUp => m_Wrapper.m_SecondPlayer_spTakeUp;
        /// <summary>
        /// Provides access to the underlying input action "SecondPlayer/spLeftOut".
        /// </summary>
        public InputAction @spLeftOut => m_Wrapper.m_SecondPlayer_spLeftOut;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_SecondPlayer; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="SecondPlayerActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(SecondPlayerActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="SecondPlayerActions" />
        public void AddCallbacks(ISecondPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_SecondPlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SecondPlayerActionsCallbackInterfaces.Add(instance);
            @spMove.started += instance.OnSpMove;
            @spMove.performed += instance.OnSpMove;
            @spMove.canceled += instance.OnSpMove;
            @spTakeUp.started += instance.OnSpTakeUp;
            @spTakeUp.performed += instance.OnSpTakeUp;
            @spTakeUp.canceled += instance.OnSpTakeUp;
            @spLeftOut.started += instance.OnSpLeftOut;
            @spLeftOut.performed += instance.OnSpLeftOut;
            @spLeftOut.canceled += instance.OnSpLeftOut;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="SecondPlayerActions" />
        private void UnregisterCallbacks(ISecondPlayerActions instance)
        {
            @spMove.started -= instance.OnSpMove;
            @spMove.performed -= instance.OnSpMove;
            @spMove.canceled -= instance.OnSpMove;
            @spTakeUp.started -= instance.OnSpTakeUp;
            @spTakeUp.performed -= instance.OnSpTakeUp;
            @spTakeUp.canceled -= instance.OnSpTakeUp;
            @spLeftOut.started -= instance.OnSpLeftOut;
            @spLeftOut.performed -= instance.OnSpLeftOut;
            @spLeftOut.canceled -= instance.OnSpLeftOut;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="SecondPlayerActions.UnregisterCallbacks(ISecondPlayerActions)" />.
        /// </summary>
        /// <seealso cref="SecondPlayerActions.UnregisterCallbacks(ISecondPlayerActions)" />
        public void RemoveCallbacks(ISecondPlayerActions instance)
        {
            if (m_Wrapper.m_SecondPlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="SecondPlayerActions.AddCallbacks(ISecondPlayerActions)" />
        /// <seealso cref="SecondPlayerActions.RemoveCallbacks(ISecondPlayerActions)" />
        /// <seealso cref="SecondPlayerActions.UnregisterCallbacks(ISecondPlayerActions)" />
        public void SetCallbacks(ISecondPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_SecondPlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SecondPlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="SecondPlayerActions" /> instance referencing this action map.
    /// </summary>
    public SecondPlayerActions @SecondPlayer => new SecondPlayerActions(this);

    // ThirdPlayer
    private readonly InputActionMap m_ThirdPlayer;
    private List<IThirdPlayerActions> m_ThirdPlayerActionsCallbackInterfaces = new List<IThirdPlayerActions>();
    private readonly InputAction m_ThirdPlayer_tpMove;
    private readonly InputAction m_ThirdPlayer_tpTakeUp;
    private readonly InputAction m_ThirdPlayer_tpLeftOut;
    /// <summary>
    /// Provides access to input actions defined in input action map "ThirdPlayer".
    /// </summary>
    public struct ThirdPlayerActions
    {
        private @GameInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public ThirdPlayerActions(@GameInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "ThirdPlayer/tpMove".
        /// </summary>
        public InputAction @tpMove => m_Wrapper.m_ThirdPlayer_tpMove;
        /// <summary>
        /// Provides access to the underlying input action "ThirdPlayer/tpTakeUp".
        /// </summary>
        public InputAction @tpTakeUp => m_Wrapper.m_ThirdPlayer_tpTakeUp;
        /// <summary>
        /// Provides access to the underlying input action "ThirdPlayer/tpLeftOut".
        /// </summary>
        public InputAction @tpLeftOut => m_Wrapper.m_ThirdPlayer_tpLeftOut;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_ThirdPlayer; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="ThirdPlayerActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(ThirdPlayerActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="ThirdPlayerActions" />
        public void AddCallbacks(IThirdPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_ThirdPlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ThirdPlayerActionsCallbackInterfaces.Add(instance);
            @tpMove.started += instance.OnTpMove;
            @tpMove.performed += instance.OnTpMove;
            @tpMove.canceled += instance.OnTpMove;
            @tpTakeUp.started += instance.OnTpTakeUp;
            @tpTakeUp.performed += instance.OnTpTakeUp;
            @tpTakeUp.canceled += instance.OnTpTakeUp;
            @tpLeftOut.started += instance.OnTpLeftOut;
            @tpLeftOut.performed += instance.OnTpLeftOut;
            @tpLeftOut.canceled += instance.OnTpLeftOut;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="ThirdPlayerActions" />
        private void UnregisterCallbacks(IThirdPlayerActions instance)
        {
            @tpMove.started -= instance.OnTpMove;
            @tpMove.performed -= instance.OnTpMove;
            @tpMove.canceled -= instance.OnTpMove;
            @tpTakeUp.started -= instance.OnTpTakeUp;
            @tpTakeUp.performed -= instance.OnTpTakeUp;
            @tpTakeUp.canceled -= instance.OnTpTakeUp;
            @tpLeftOut.started -= instance.OnTpLeftOut;
            @tpLeftOut.performed -= instance.OnTpLeftOut;
            @tpLeftOut.canceled -= instance.OnTpLeftOut;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ThirdPlayerActions.UnregisterCallbacks(IThirdPlayerActions)" />.
        /// </summary>
        /// <seealso cref="ThirdPlayerActions.UnregisterCallbacks(IThirdPlayerActions)" />
        public void RemoveCallbacks(IThirdPlayerActions instance)
        {
            if (m_Wrapper.m_ThirdPlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="ThirdPlayerActions.AddCallbacks(IThirdPlayerActions)" />
        /// <seealso cref="ThirdPlayerActions.RemoveCallbacks(IThirdPlayerActions)" />
        /// <seealso cref="ThirdPlayerActions.UnregisterCallbacks(IThirdPlayerActions)" />
        public void SetCallbacks(IThirdPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_ThirdPlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ThirdPlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="ThirdPlayerActions" /> instance referencing this action map.
    /// </summary>
    public ThirdPlayerActions @ThirdPlayer => new ThirdPlayerActions(this);

    // FourPlayer
    private readonly InputActionMap m_FourPlayer;
    private List<IFourPlayerActions> m_FourPlayerActionsCallbackInterfaces = new List<IFourPlayerActions>();
    private readonly InputAction m_FourPlayer_fopMove;
    private readonly InputAction m_FourPlayer_fopTakeUp;
    private readonly InputAction m_FourPlayer_fopLeftOut;
    /// <summary>
    /// Provides access to input actions defined in input action map "FourPlayer".
    /// </summary>
    public struct FourPlayerActions
    {
        private @GameInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public FourPlayerActions(@GameInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "FourPlayer/fopMove".
        /// </summary>
        public InputAction @fopMove => m_Wrapper.m_FourPlayer_fopMove;
        /// <summary>
        /// Provides access to the underlying input action "FourPlayer/fopTakeUp".
        /// </summary>
        public InputAction @fopTakeUp => m_Wrapper.m_FourPlayer_fopTakeUp;
        /// <summary>
        /// Provides access to the underlying input action "FourPlayer/fopLeftOut".
        /// </summary>
        public InputAction @fopLeftOut => m_Wrapper.m_FourPlayer_fopLeftOut;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_FourPlayer; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="FourPlayerActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(FourPlayerActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="FourPlayerActions" />
        public void AddCallbacks(IFourPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_FourPlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FourPlayerActionsCallbackInterfaces.Add(instance);
            @fopMove.started += instance.OnFopMove;
            @fopMove.performed += instance.OnFopMove;
            @fopMove.canceled += instance.OnFopMove;
            @fopTakeUp.started += instance.OnFopTakeUp;
            @fopTakeUp.performed += instance.OnFopTakeUp;
            @fopTakeUp.canceled += instance.OnFopTakeUp;
            @fopLeftOut.started += instance.OnFopLeftOut;
            @fopLeftOut.performed += instance.OnFopLeftOut;
            @fopLeftOut.canceled += instance.OnFopLeftOut;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="FourPlayerActions" />
        private void UnregisterCallbacks(IFourPlayerActions instance)
        {
            @fopMove.started -= instance.OnFopMove;
            @fopMove.performed -= instance.OnFopMove;
            @fopMove.canceled -= instance.OnFopMove;
            @fopTakeUp.started -= instance.OnFopTakeUp;
            @fopTakeUp.performed -= instance.OnFopTakeUp;
            @fopTakeUp.canceled -= instance.OnFopTakeUp;
            @fopLeftOut.started -= instance.OnFopLeftOut;
            @fopLeftOut.performed -= instance.OnFopLeftOut;
            @fopLeftOut.canceled -= instance.OnFopLeftOut;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="FourPlayerActions.UnregisterCallbacks(IFourPlayerActions)" />.
        /// </summary>
        /// <seealso cref="FourPlayerActions.UnregisterCallbacks(IFourPlayerActions)" />
        public void RemoveCallbacks(IFourPlayerActions instance)
        {
            if (m_Wrapper.m_FourPlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="FourPlayerActions.AddCallbacks(IFourPlayerActions)" />
        /// <seealso cref="FourPlayerActions.RemoveCallbacks(IFourPlayerActions)" />
        /// <seealso cref="FourPlayerActions.UnregisterCallbacks(IFourPlayerActions)" />
        public void SetCallbacks(IFourPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_FourPlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FourPlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="FourPlayerActions" /> instance referencing this action map.
    /// </summary>
    public FourPlayerActions @FourPlayer => new FourPlayerActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_Pause;
    private readonly InputAction m_UI_Resume;
    /// <summary>
    /// Provides access to input actions defined in input action map "UI".
    /// </summary>
    public struct UIActions
    {
        private @GameInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public UIActions(@GameInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "UI/Pause".
        /// </summary>
        public InputAction @Pause => m_Wrapper.m_UI_Pause;
        /// <summary>
        /// Provides access to the underlying input action "UI/Resume".
        /// </summary>
        public InputAction @Resume => m_Wrapper.m_UI_Resume;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="UIActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="UIActions" />
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @Resume.started += instance.OnResume;
            @Resume.performed += instance.OnResume;
            @Resume.canceled += instance.OnResume;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="UIActions" />
        private void UnregisterCallbacks(IUIActions instance)
        {
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @Resume.started -= instance.OnResume;
            @Resume.performed -= instance.OnResume;
            @Resume.canceled -= instance.OnResume;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="UIActions.UnregisterCallbacks(IUIActions)" />.
        /// </summary>
        /// <seealso cref="UIActions.UnregisterCallbacks(IUIActions)" />
        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="UIActions.AddCallbacks(IUIActions)" />
        /// <seealso cref="UIActions.RemoveCallbacks(IUIActions)" />
        /// <seealso cref="UIActions.UnregisterCallbacks(IUIActions)" />
        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="UIActions" /> instance referencing this action map.
    /// </summary>
    public UIActions @UI => new UIActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "FirstPlayer" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="FirstPlayerActions.AddCallbacks(IFirstPlayerActions)" />
    /// <seealso cref="FirstPlayerActions.RemoveCallbacks(IFirstPlayerActions)" />
    public interface IFirstPlayerActions
    {
        /// <summary>
        /// Method invoked when associated input action "fpMove" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFpMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "fpTakeUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFpTakeUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "fpLeftOut" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFpLeftOut(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "SecondPlayer" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="SecondPlayerActions.AddCallbacks(ISecondPlayerActions)" />
    /// <seealso cref="SecondPlayerActions.RemoveCallbacks(ISecondPlayerActions)" />
    public interface ISecondPlayerActions
    {
        /// <summary>
        /// Method invoked when associated input action "spMove" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "spTakeUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpTakeUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "spLeftOut" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpLeftOut(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "ThirdPlayer" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="ThirdPlayerActions.AddCallbacks(IThirdPlayerActions)" />
    /// <seealso cref="ThirdPlayerActions.RemoveCallbacks(IThirdPlayerActions)" />
    public interface IThirdPlayerActions
    {
        /// <summary>
        /// Method invoked when associated input action "tpMove" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTpMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "tpTakeUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTpTakeUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "tpLeftOut" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTpLeftOut(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "FourPlayer" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="FourPlayerActions.AddCallbacks(IFourPlayerActions)" />
    /// <seealso cref="FourPlayerActions.RemoveCallbacks(IFourPlayerActions)" />
    public interface IFourPlayerActions
    {
        /// <summary>
        /// Method invoked when associated input action "fopMove" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFopMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "fopTakeUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFopTakeUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "fopLeftOut" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFopLeftOut(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "UI" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="UIActions.AddCallbacks(IUIActions)" />
    /// <seealso cref="UIActions.RemoveCallbacks(IUIActions)" />
    public interface IUIActions
    {
        /// <summary>
        /// Method invoked when associated input action "Pause" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPause(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Resume" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnResume(InputAction.CallbackContext context);
    }
}
